import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AI } from "~/actions/ai";
import { cn } from "~/lib/utils";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // @ts-ignore
    <AI>
      <html lang="en">
        <body
          className={cn(
            inter.className,
            "md:flex md:justify-center md:items-center md:mx-auto md:max-w-screen-md",
          )}
        >
          {children}
        </body>
      </html>
    </AI>
  );
}
